extern  calloc
extern  malloc

STRUC node
    .val:   resd 1
    .next:  resd 1
ENDSTRUC

;------------------------------------------------------------------------------
; push:
;
; Description:
; Receives: <argument list>
; Returns:  <return list>
; Requires: <requirements>
; Notes:    <notes>
; Algo:     <algorithm>
;-------------------------------------------------------------------------------

    
    
    ret
    
; End  <procedure_label> -------------------------------------------------------
